codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "50...80"
  status:
    project:
      default:
        # basic
        target: 80%
        threshold: 3%
        flags:
          - unit
        paths:
          - "src"
        # advanced settings
        branches:
          - master
        if_ci_failed: error #success, failure, error, ignore
        informational: true
        only_pulls: false

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
