version = 1

test_patterns = ["*.test.js"]

exclude_patterns = [
  "*/js/lib/*",
  "*mSat.js*",
  "*/offline/*",
  ]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["jquery"]
