---
name: Feature Request
description: Request a new feature
title: "[Feature Req]: "
labels: ["feature : addition"]
assignees:
  - "thkruz"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to provide feedback on what you want added!  
  - type: dropdown
    id: role
    attributes:
      label: As a...
      description: Which role most closely represents you?
      options:
        - User
        - Developer
    validations:
      required: true
  - type: "input"
    id: request
    attributes:
      label: I want...
      description: Tell us what you want to see added.
    validations:
      required: true
  - type: "input"
      id: goal
      attributes:
        label: So that...
        description: Tell us what your end goal is.
      validations:
        required: true
  - type: markdown
    attributes:
      value: |
        Help us understand how we will know we met your needs.
  - type: "input"
    id: given
    attributes:
      label: Given...
      description: Tell us about any starting conditions.
    validations:
      required: true
  - type: "input"
    id: when
    attributes:
      label: When...
      description: Tell us about any actions that would happen.
    validations:
      required: true
  - type: "input"
      id: then
      attributes:
        label: Then...
        description: Tell us what should happen.
      validations:
        required: true