name: Jest Tests Inline
on:
  workflow_dispatch:
jobs:
  jest:
    name: Jest Tests
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v2
      # Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "17"
      # Get Node Modules from Cache
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-
            ${{ env.cache-name }}-
            ${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      # Ensure Node Modules Setup
      - name: Install Dependencies
        run: npm ci --ignore-scripts
      # Set Timezone to match snapshots
      - name: Set Timezone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "America/New_York"
      # Unit Tests for Code Coverage
      - name: Test
        run: npm test -- --runInBand
