name: Node.js CI

on: 
  workflow_dispatch:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm install    
    - run: npm run build:dev
    - run: npm http
    - run: npm run test
    - run: node ./node_modules/.bin/codecov
