name: Node.js CI

on: 
  workflow_dispatch:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: npm install --save-dev        
    - run: npm run build
    - run: npm run test      
    - run: node ./node_modules/.bin/codecov
