name: Node.js CI

on: 
  workflow_run:
    workflows: ["Run Tests"]
  pull_request:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm install
    - run: npm run stage
    - run: npm run build-dev
    - run: npm test
