name: Visualizer
on:
    workflow_dispatch:
    push:
      branches:
        - main
jobs:
  update-visualizer:
    name: Update Visualizer
    runs-on: ubuntu-latest

    steps:
      - name: Get Code
        uses: actions/checkout

      - name: Repo Visualizer
        uses: githubocto/repo-visualizer@0.9.1
        with:
          output_file: "diagram.svg"
          excluded_paths: "dist,node_modules"
