name: Visualizer
on:
    workflow_dispatch:
    push:
      branches:
        - develop
jobs:
  update-visualizer:
    name: Update Visualizer
    runs-on: ubuntu-latest

    steps:
      - name: Get Code
        uses: actions/checkout@v2

      - name: Run Visualizer
        uses: githubocto/repo-visualizer